gcc -c -fPIC org_mymmsc_api_encoding_Charsets.c -I ./ -I ~/apps/jdk/include -I ~/apps/jdk/include/linux -I ~/include
gcc -rdynamic -shared -fPIC -o mymmsc-charset.so org_mymmsc_api_encoding_Charsets.o ~/lib/libenca.a
