/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mymmsc_api_encoding_Charsets */

#ifndef _Included_org_mymmsc_api_encoding_Charsets
#define _Included_org_mymmsc_api_encoding_Charsets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mymmsc_api_encoding_Charsets
 * Method:    detect
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mymmsc_api_encoding_Charsets_detect
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
